CREATE DATABASE IF NOT EXISTS necco;
USE necco;

CREATE TABLE IF NOT EXISTS User (
    id_         BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    createdAt   DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt   DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    email       VARCHAR(321) DEFAULT '' NOT NULL,
    password_   VARCHAR(128) NOT NULL,
    isAdmin     BOOLEAN DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS History (
    id_           BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    createdAt     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    payerUserId   BIGINT UNSIGNED NOT NULL,
    providedAt    DATETIME NOT NULL,
    payeeUserId   BIGINT UNSIGNED NOT NULL,
    what          VARCHAR(1024) NOT NULL,
    priceNecco    INT DEFAULT 0 NOT NULL,
    priceYen      INT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS Profile (
    id_           BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    createdAt     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    userId        BIGINT UNSIGNED NOT NULL,
    lastName      VARCHAR(128)    NOT NULL,
    firstName     VARCHAR(128)    NOT NULL,
    lastKanaName  VARCHAR(128)    NOT NULL,
    firstKanaName VARCHAR(128)    NOT NULL,
    nickName      VARCHAR(128)    DEFAULT '' NOT NULL,
    phoneNumber   VARCHAR(32)     DEFAULT '' NOT NULL,
    faxNumber     VARCHAR(32)     DEFAULT '' NOT NULL,
    prefectureId INT UNSIGNED DEFAULT 1  NOT NULL,
    address       VARCHAR(16)  DEFAULT '' NOT NULL,
    streetAddress VARCHAR(128) DEFAULT '' NOT NULL,
    latitude      DOUBLE(7,5) DEFAULT 0.0 NOT NULL,
    longitude     DOUBLE(8,5) DEFAULT 0.0 NOT NULL,
    profile       VARCHAR(4096)   DEFAULT '' NOT NULL
);

/* http://kikakurui.com/x0/X0401-1973-01.html */
CREATE TABLE IF NOT EXISTS Prefecture (
    id_        INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    createdAt  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name_ VARCHAR(16) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS UsersAbility (
    id_        BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    createdAt  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    userId     BIGINT UNSIGNED NOT NULL,
    abilityId  BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS Ability (
    id_        BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    createdAt  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    genre      VARCHAR(1024) DEFAULT '' NOT NULL,
    detail     VARCHAR(1024) DEFAULT '' NOT NULL
);

CREATE TABLE IF NOT EXISTS UsersRequest (
    id_        BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    createdAt  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    userId     BIGINT UNSIGNED NOT NULL,
    requestId  BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS Request (
    id_        BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    createdAt  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    genre      VARCHAR(1024) DEFAULT '' NOT NULL,
    detail     VARCHAR(1024) DEFAULT '' NOT NULL
);
