CREATE DATABASE IF NOT EXISTS necco;
USE necco;

CREATE TABLE IF NOT EXISTS User (
    id          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    email       VARCHAR(321) DEFAULT '' NOT NULL,
    password_   VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS History (
  id            BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  created_at    DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at    DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  payer_user_id BIGINT UNSIGNED NOT NULL,
  provided_at   DATETIME NOT NULL,
  payee_user_id BIGINT UNSIGNED NOT NULL,
  what          VARCHAR(1024) NOT NULL,
  price_necco   INT DEFAULT 0 NOT NULL,
  price_yen     INT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS Profile (
    id            BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    created_at    DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id       BIGINT UNSIGNED NOT NULL,
    name_         VARCHAR(128)    NOT NULL,
    kana          VARCHAR(128)    NOT NULL,
    nickname      VARCHAR(128)    DEFAULT '' NOT NULL,
    phone         VARCHAR(32)     DEFAULT '' NOT NULL,
    fax           VARCHAR(32)     DEFAULT '' NOT NULL,
    prefecture_id INT UNSIGNED DEFAULT 1  NOT NULL,
    city          VARCHAR(16)  DEFAULT '' NOT NULL,
    street        VARCHAR(128) DEFAULT '' NOT NULL,
    latitude      DOUBLE(7,5) DEFAULT 0.0 NOT NULL,
    longitude     DOUBLE(8,5) DEFAULT 0.0 NOT NULL,
    profile       VARCHAR(4096)   DEFAULT '' NOT NULL
);

/* http://kikakurui.com/x0/X0401-1973-01.html */
CREATE TABLE IF NOT EXISTS Prefecture (
    id         INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name_ VARCHAR(16) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS UsersAbility (
    id         BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id    BIGINT UNSIGNED NOT NULL,
    ability_id BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS Ability (
    id         BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    genre      VARCHAR(1024) DEFAULT '' NOT NULL,
    detail     VARCHAR(1024) DEFAULT '' NOT NULL
);

CREATE TABLE IF NOT EXISTS UsersRequest (
    id         BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id    BIGINT UNSIGNED NOT NULL,
    request_id BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS Request (
    id         BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    genre      VARCHAR(1024) DEFAULT '' NOT NULL,
    detail     VARCHAR(1024) DEFAULT '' NOT NULL
);
